language: ruby
rvm:
  - 2.2.2
before_install:  cd thinknetica_qna
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

addons:
  postgresql: "9.4"

script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec rspec ./spec/acceptance/mark_best_answer_spec.rb --color --require spec_helper
